name: informasinn
description: "Simple project that calls the huggingface API to convert user entered data into information."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  url_launcher_web: ^2.4.1
  flutter_dotenv: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  envied_generator: ^1.3.1
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
